<!DOCTYPE html> 
<html> 
<head> 
	<title>My Page</title> 
	<meta http-equiv="content-type" content="text/html;charset=windows-1255"> 
	<meta name="viewport" content="width=device-width, initial-scale=1"> 
	<link rel="stylesheet" href="http://code.jquery.com/mobile/1.0/jquery.mobile-1.0.min.css" />
	<script type="text/javascript" src="http://code.jquery.com/jquery-1.6.4.min.js"></script>
	<script type="text/javascript" src="http://code.jquery.com/mobile/1.0/jquery.mobile-1.0.min.js"></script>
	<script type="text/javascript">
	$(document).ready(function() {
		$.getJSON('index/list', function(data) {
			  var items = [];
			  $.each(data, function(key, val) {
				if (val.type != "sessions") { 
			    	items.push('<li data-theme="b"><a href="index.html" >' + val.date + '</a></li>');
				} else {
			    	items.push('<li data-theme="c"><a href="index.html" >' + val.date + '</a></li>');
				}
			  });
  			  $("#mainList").append(items.join(''));
			  $('#mainList').listview('refresh');
			});
	});
	</script>
	
</head> 
<body> 
<div data-role="page">

	<div data-role="header" data-position="inline">
		<h1>Reports</h1>
		<a href="index/reportshift" data-icon="arrow-l" class="ui-btn-left">Previous Month</a>
		<a href="index/reportsession" data-icon="arrow-r" data-iconpos="right" class="ui-btn-right">Next Month</a>
	</div>
	
	<div data-role="content">	
		<div class="ui-grid-b">
			<div class="ui-block-a"><a href="index/reportshift" data-role="button" data-icon="plus">Report Shift</a></div>
			<div class="ui-block-b"><?= $this->month ?></div>
			<div class="ui-block-c"><a href="index/reportsession" data-role="button" data-icon="plus">Report Sessions</a></div>
		</div><!-- /grid-b -->	
	</div><!-- /content -->

	<div data-role="content">	
		<ul id="mainList" data-role="listview" data-theme="b">
		</ul>
	</div><!-- /content -->

	
	
</div><!-- /page -->

</body>
</html>

