<!DOCTYPE html> 
<html> 
<head> 
	<title>My Page</title> 
	<meta http-equiv="content-type" content="text/html;charset=windows-1255"> 
	<meta name="viewport" content="width=device-width, initial-scale=1"> 
	<link rel="stylesheet" href="http://code.jquery.com/mobile/1.0/jquery.mobile-1.0.min.css" />
	<script type="text/javascript" src="http://code.jquery.com/jquery-1.6.4.min.js"></script>
	<script type="text/javascript" src="http://code.jquery.com/mobile/1.0/jquery.mobile-1.0.min.js"></script>
	<script data-main="scripts/index/index" src="<?= $this->baseUrl("scripts/require.js") ?>"></script>	
</head> 
<body> 
<div data-role="page">

	<div data-role="header" data-position="inline">
		<h1>Reports</h1>
		<a href="index/" data-icon="arrow-l" class="ui-btn-left">Previous Month</a>
		<a href="index/" data-icon="arrow-r" data-iconpos="right" class="ui-btn-right">Next Month</a>
	</div>
	
	<div data-role="content">	
		<div class="ui-grid-b">
			<div class="ui-block-a"></div>
			<div class="ui-block-b"><?= $this->month ?></div>
			<div class="ui-block-c"><a href="<?= $this->url(array('controller'=>'index', 'action' => 'insert'))?>/" data-role="button" data-icon="plus" rel="external">Report</a></div>
		</div><!-- /grid-b -->	
	</div><!-- /content -->

	<div data-role="content">	
		<ul id="mainList" data-role="listview" data-theme="b">
		</ul>
	</div><!-- /content -->

</div><!-- /page -->

</body>
</html>

