<!DOCTYPE html> 
<html> 
<head> 
	<title>My Page</title> 
	<meta http-equiv="content-type" content="text/html;charset=windows-1255"> 
	<meta name="viewport" content="width=device-width, initial-scale=1"> 
	<link rel="stylesheet" href="http://code.jquery.com/mobile/1.0/jquery.mobile-1.0.min.css" />
	<script type="text/javascript" src="http://code.jquery.com/jquery-1.6.4.min.js"></script>
	<script type="text/javascript" src="http://code.jquery.com/mobile/1.0/jquery.mobile-1.0.min.js"></script>
	<script data-main="/scripts/index/insert" src="<?= $this->baseUrl() ?>/scripts/require.js"></script>	
</head> 
<body> 
<div data-role="page">

	<div data-role="header" data-position="inline">
		<a href="<?= $this->url(array('controller'=>'index', 'action' => 'index'))?>" data-icon="delete" rel="external">Cancel</a>
		<h1>Event</h1>
		<a href="<?= $this->url(array('controller'=>'index', 'action' => 'index'))?>" id="save-btn" data-icon="check" data-theme="b" rel="external">Save</a>
	</div>
	
	<div data-role="content">	
		<form id="event-form">
			<fieldset data-role="controlgroup" data-type="horizontal" >
				<input type="radio" name="radio-choice-1" id="radio-choice-1" value="choice-1" checked="checked" />
	     		<label for="radio-choice-1">Shift</label>
		     	<input type="radio" name="radio-choice-1" id="radio-choice-2" value="choice-2"  />
		     	<label for="radio-choice-2">Sessions</label>
			</fieldset>
			
			<fieldset data-role="controlgroup" data-type="horizontal"> 
			
				<select name="select-choice-month" id="select-choice-month">
					<option>Month</option>
					<option value="1">1</option>
					<option value="2">2</option>
					<option value="3">3</option>
					<option value="4">4</option>
					<option value="5">5</option>
					<option value="6">6</option>
					<option value="7">7</option>
					<option value="8">8</option>
					<option value="9">9</option>
					<option value="10">10</option>
					<option value="11">11</option>
					<option value="12">12</option>
				</select>
				
				<select name="select-choice-day" id="select-choice-day">
					<option>Day</option>
					<option value="1">1</option>
					<option value="2">2</option>
					<option value="3">3</option>
					<option value="4">4</option>
					<option value="5">5</option>
					<option value="6">6</option>
					<option value="7">7</option>
					<option value="8">8</option>
					<option value="9">9</option>
					<option value="10">10</option>
					<option value="11">11</option>
					<option value="12">12</option>
					<option value="13">13</option>
					<option value="14">14</option>
					<option value="15">15</option>
					<option value="16">16</option>
					<option value="17">17</option>
					<option value="18">18</option>
					<option value="19">19</option>
					<option value="20">20</option>
					<option value="21">21</option>
					<option value="22">22</option>
					<option value="23">23</option>
					<option value="24">24</option>
					<option value="25">25</option>
					<option value="26">26</option>
					<option value="27">27</option>
					<option value="28">28</option>
					<option value="29">29</option>
					<option value="30">30</option>
					<option value="31">31</option>
				</select>
				
				<select name="select-choice-year" id="select-choice-year">
					<option>Year</option>
					<option value="2012">2012</option>
					<option value="2013">2013</option>
					<option value="2014">2014</option>
				</select>
			</fieldset>		
			
			<div data-role="fieldcontain" class="ui-hide-label">
				<label for="username">Comments:</label>
				<input type="text" name="comments" id="comments" value="" placeholder="Comments"/>
			</div>
		</form>
		
		
	</div><!-- /content -->
	
</div><!-- /page -->

</body>
</html>

