<!DOCTYPE html> 
<html> 
<head> 
	<title>My Page</title> 
	<meta http-equiv="content-type" content="text/html;charset=windows-1255"> 
	<meta name="viewport" content="width=device-width, initial-scale=1"> 
	<link rel="stylesheet" href="http://code.jquery.com/mobile/1.0/jquery.mobile-1.0.min.css" />
	<script type="text/javascript" src="http://code.jquery.com/jquery-1.6.4.min.js"></script>
	<script type="text/javascript" src="http://code.jquery.com/mobile/1.0/jquery.mobile-1.0.min.js"></script>
	<script type="text/javascript" src="<?= $this->baseUrl() ?>/scripts/require.js"></script>
	<script type="text/javascript">
	  require.config({
	    baseUrl: "<?= $this->baseUrl() ?>",
	  });
	  require( ["scripts/index/update", "scripts/url"]);
	</script>
	
</head> 
<body> 
<div data-role="page">

	<div data-role="header" data-position="inline">
		<a href="<?= $this->url(array('controller'=>'index', 'action' => 'index'))?>" data-icon="delete" rel="external">Cancel</a>
		<h1>Update</h1>
		<a href="<?= $this->url(array('controller'=>'index', 'action' => 'index'))?>" id="save-btn" data-icon="check" data-theme="b" rel="external">Save</a>
	</div>
	
	<div data-role="content">
		<form id="event-form">

			<div data-role="fieldcontain" class="ui-hide-label">
				<label for="username">Comments:</label>
				<input type="text" name="comments" id="comments" value="" placeholder="Comments"/>
			</div>

			<a href="<?= $this->url(array('controller'=>'index', 'action' => 'index'))?>" data-role="button" id="delete-btn" data-icon="delete" data-theme="e" rel="external">Delete</a>
		</form>
	
	</div><!-- /content -->
	
</div><!-- /page -->

</body>
</html>

